### ISSUE TITLE
Menampilkan gambar yang terlalu lama

### ISSUE THREAD

**Issue by Whitnu12** [AdityaFitrianaNS/myportfolio1#1]
Hallo mas, ini sedikit saran dari saya, karena ukuran gambar masnya terlalu besar, dan terlalu lama untuk di load ke websitenya, saya sarankan sih di konversikan jadi ekstensi webp atau jfif tanpa mengubah resolusinya

kalau boleh semua gambarnya di konversikan jadi demikian

**Comment by AdityaFitrianaNS** [comment]
Halo juga mas, maaf ya baru cek isi email, oke mas terimakasih banyak atas
sarannya, kebetulan memang akan ada perubahan dan mau di update reponya.
sekali lagi terimakasih ya mas😊.

Pada tanggal Sab, 9 Okt 2021 pukul 15.16 Whitnu Nastain <
***@***.***> menulis:
